version: "3"
services:
  my-app:
    image: 471112792301.dkr.ecr.us-east-1.amazonaws.com/my-app:1.1
    ports:
      - "3000:3000"
    volumes:
      - mongo-data:/data/db
    depends_on:
      - mongodb
      - mongo-express

  mongodb:
    image: mongo:4.2.1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
